version: '3.3'
services:
  nginx:
    build:
      context: .
      dockerfile: ../../../.Bricks/Containers/Nginx/${project_os}/${project_os_version}/foundation
    image: custom-${project_os_lowercase}-${project_os_version}-v1
    hostname: nginx
    tty: true
    container_name: ${project_name}-nginx
    ports:
      - 127.0.0.1:10100:10100
    networks:
      - net

networks:
  net:
    name: ${project_name}-net
    driver: bridge
