version: '3.3'
services:
  base:
    build:
      context: .
      dockerfile: ../../../.Bricks/Containers/Base/${project_os}/${project_os_version}/foundation
    image: custom-${project_os_lowercase}-${project_os_version}-v1
    hostname: base
    tty: true
    container_name: ${project_name}-base
    networks:
      - net

networks:
  net:
    name: ${project_name}-net
    driver: bridge
