version: '3.3'
services:
  mariadb:
    build:
      context: .
      dockerfile: ../../../.Bricks/Containers/MariaDB/${project_os}/${project_os_version}/foundation
    image: custom-${project_os_lowercase}-${project_os_version}-v1
    hostname: mariadb
    tty: true
    container_name: ${project_name}-mariadb
    networks:
      - net

networks:
  net:
    name: ${project_name}-net
    driver: bridge
